export const CREATE_PLAYER_START = 'CREATE_PLAYER_START';
export const CREATE_PLAYER_SUCCESS = 'CREATE_PLAYER_SUCCESS';
export const CREATE_PLAYER_FAILED = 'CREATE_PLAYER_FAILED';

export const LOAD_ROSTER_START = 'LOAD_ROSTER_START';
export const LOAD_ROSTER_SUCCESS = 'LOAD_ROSTER_SUCCESS';
export const LOAD_ROSTER_FAILED = 'LOAD_ROSTER_FAILED';