export const CREATE_PLAYER_START = 'CREATE_PLAYER_START';
export const CREATE_PLAYER_SUCCESS = 'CREATE_PLAYER_SUCCESS';
export const CREATE_PLAYER_FAILED = 'CREATE_PLAYER_FAILED';

export const DELETE_PLAYER_START = 'DELETE_PLAYER_START';
export const DELETE_PLAYER_SUCCESS = 'DELETE_PLAYER_SUCCESS';
export const DELETE_PLAYER_FAILED = 'DELETE_PLAYER_FAILED';

export const LOAD_ROSTER_START = 'LOAD_ROSTER_START';
export const LOAD_ROSTER_SUCCESS = 'LOAD_ROSTER_SUCCESS';
export const LOAD_ROSTER_FAILED = 'LOAD_ROSTER_FAILED';

export const UPDATE_PLAYER_START = 'UPDATE_PLAYER_START';
export const UPDATE_PLAYER_FAILED = 'UPDATE_PLAYER_FAILED';